// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Options":{
        "en":"Settings",
        "de":"Einstellungen",
        "ru":"Настройки",
        "pt":"Configurações",
        "nl":"instellingen",
        "fr":"Paramètres",
        "it":"Impostazioni",
        "es":"Configuraciones",
        "pl":"Ustawienia"
    },
    "serialPort":{
        "en":"Serial port",
        "de":"Serielle Schnittstelle",
        "ru":"Серийный порт",
        "pt":"Porta serial",
        "nl":"Seriële poort",
        "fr":"Port série",
        "it":"Porta seriale",
        "es":"Puerto serial",
        "pl":"Port szeregowy"
    },
    "serialBaudRate":{
        "en":"Serial baud rate",
        "de":"Serielle Baudrate",
        "ru":"Скорость передачи",
        "pt":"Taxa de transmissão em série",
        "nl":"Seriële baudrate",
        "fr":"Vitesse de transmission en série",
        "it":"Baud rate seriale",
        "es":"Velocidad en baudios en serie",
        "pl":"Szeregowa prędkość transmisji"
    },
    "Select port": {
        "en": "Select port",
        "de": "Wählen Sie den Port aus",
        "ru": "Выбрать порт",
        "pt": "Selecione a porta",
        "nl": "Selecteer poort",
        "fr": "Sélectionnez un port",
        "it": "Seleziona porta",
        "es": "Seleccionar puerto",
        "pl": "Wybierz port"
    },
    "ID":{
        "en":"ID",
        "de":"ID",
        "ru":"ID",
        "pt":"ID",
        "nl":"ID",
        "fr":"ID"
    },
    "Update unchanged states":{
        "en":"Update unchanged states",
        "de":"Unveränderte Werte aktualisieren",
        "ru":"Update unchanged states",
        "pt":"Update unchanged states",
        "nl":"Update unchanged states",
        "fr":"Update unchanged states",
        "it":"Update unchanged states",
        "es":"Update unchanged states",
        "pl":"Update unchanged states"
    },
    "AES keys":{
        "en":"AES keys",
        "de":"AES Schlüssel",
        "ru":"AES keys",
        "pt":"AES keys",
        "nl":"AES keys",
        "fr":"AES keys",
        "es":"AES keys",
        "pl":"AES keys",
        "it":"AES keys"
    },
    "AES key":{
        "en":"AES key",
        "de":"AES Schlüssel",
        "ru":"AES key",
        "pt":"AES key",
        "nl":"AES key",
        "fr":"AES key",
        "es":"AES key",
        "pl":"AES key",
        "it":"AES key"
    },
    "Device address":{
        "en":"Device address",
        "de":"Geräte Adresse",
        "ru":"Device address",
        "pt":"Device address",
        "nl":"Device address",
        "fr":"Device address",
        "es":"Device address",
        "pl":"Device address",
        "it":"Device address"
    },
    "wMBus Receiver":{
        "en":"wMBus Receiver",
        "de":"wMBus Empfänger",
        "ru":"wMBus Receiver",
        "pt":"wMBus Receiver",
        "nl":"wMBus Receiver",
        "fr":"wMBus Receiver",
        "es":"wMBus Receiver",
        "pl":"wMBus Receiver",
        "it":"wMBus Receiver"
    }
};

