/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "AES key": {                                     "en": "AES key",                                         "de": "AES Schlüssel",                                   "ru": "Ключ AES",                                        "pt": "Chave AES",                                       "nl": "AES-sleutel",                                     "fr": "clé AES",                                         "it": "Tasto AES",                                       "es": "Clave AES",                                       "pl": "Klucz AES",                                       "zh-cn": "AES 密钥"},
    "AES keys": {                                    "en": "AES keys",                                        "de": "AES Schlüssel",                                   "ru": "Ключи AES",                                       "pt": "Chaves AES",                                      "nl": "AES-sleutels",                                    "fr": "Clés AES",                                        "it": "Tasti AES",                                       "es": "Claves AES",                                      "pl": "Klawisze AES",                                    "zh-cn": "AES 密钥"},
    "Blocked Devices": {                             "en": "Blocked Devices",                                 "de": "Blockierte Geräte",                               "ru": "Заблокированные устройства",                      "pt": "Dispositivos Bloqueados",                         "nl": "Geblokkeerde apparaten",                          "fr": "Appareils bloqués",                               "it": "Dispositivi bloccati",                            "es": "Dispositivos bloqueados",                         "pl": "Zablokowane urządzenia",                          "zh-cn": "被阻止的设备"},
    "Cache for compact frames support": {            "en": "Cache for compact frames support",                "de": "Cache für Kompakt-Telegramme",                    "ru": "Кэш для поддержки компактных фреймов",            "pt": "Cache para suporte a frames compactos",           "nl": "Cache voor ondersteuning van compacte frames",    "fr": "Cache pour la prise en charge des cadres compacts", "it": "Cache per supporto di frame compatti",            "es": "Caché para compatibilidad con marcos compactos",  "pl": "Pamięć podręczna do obsługi kompaktowych ramek",  "zh-cn": "支持紧凑帧的缓存"},
    "Custom serial port": {                          "en": "Custom serial port",                              "de": "Benutzerdefinierte Schnittstelle",                "ru": "Пользовательский последовательный порт",          "pt": "Porta serial personalizada",                      "nl": "Aangepaste seriële poort",                        "fr": "Port série personnalisé",                         "it": "Porta seriale personalizzata",                    "es": "Puerto serie personalizado",                      "pl": "Niestandardowy port szeregowy",                   "zh-cn": "自定义串口"},
    "Device address": {                              "en": "Device address",                                  "de": "Geräte Adresse",                                  "ru": "Адрес устройства",                                "pt": "Endereço do dispositivo",                         "nl": "Apparaatadres",                                   "fr": "Adresse de l'appareil",                           "it": "Indirizzo del dispositivo",                       "es": "Dirección del dispositivo",                       "pl": "Adres urządzenia",                                "zh-cn": "设备地址"},
    "Force energy units to kWh": {                   "en": "Force energy units to kWh",                       "de": "Energieeinheiten auf kWh setzen",                 "ru": "Силовые единицы энергии в кВтч",                  "pt": "Forçar unidades de energia a kWh",                "nl": "Forceer energie-eenheden naar kWh",               "fr": "Forcer les unités d'énergie au kWh",              "it": "Forza unità di energia a kWh",                    "es": "Forzar unidades de energía a kWh",                "pl": "Wymuś jednostki energii do kWh",                  "zh-cn": "强制能量单位为 kWh"},
    "ID": {                                          "en": "ID",                                              "de": "ID",                                              "ru": "ID",                                              "pt": "ID",                                              "nl": "ID",                                              "fr": "ID",                                              "it": "ID",                                              "es": "IDENTIFICACIÓN",                                  "pl": "NS",                                              "zh-cn": "ID"},
    "Options": {                                     "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Настройки",                                       "pt": "Configurações",                                   "nl": "instellingen",                                    "fr": "Paramètres",                                      "it": "Impostazioni",                                    "es": "Configuraciones",                                 "pl": "Ustawienia",                                      "zh-cn": "设置"},
    "Select port": {                                 "en": "Select port",                                     "de": "Wählen Sie den Port aus",                         "ru": "Выбрать порт",                                    "pt": "Selecione a porta",                               "nl": "Selecteer poort",                                 "fr": "Sélectionnez un port",                            "it": "Seleziona porta",                                 "es": "Seleccionar puerto",                              "pl": "Wybierz port",                                    "zh-cn": "选择端口"},
    "Temporarily block device after consecutive failures": {"en": "Temporarily block device after consecutive failures", "de": "Gerät nach mehrfachen Fehlern temporär blockieren", "ru": "Временно заблокировать устройство после последовательных сбоев", "pt": "Bloqueie temporariamente o dispositivo após falhas consecutivas", "nl": "Apparaat tijdelijk blokkeren na opeenvolgende storingen", "fr": "Bloquer temporairement l'appareil après des pannes consécutives", "it": "Bloccare temporaneamente il dispositivo dopo guasti consecutivi", "es": "Bloquear temporalmente el dispositivo después de fallas consecutivas", "pl": "Tymczasowo blokuj urządzenie po kolejnych awariach", "zh-cn": "连续失败后临时阻止设备"},
    "Update unchanged states": {                     "en": "Update unchanged states",                         "de": "Unveränderte Werte aktualisieren",                "ru": "Обновить неизмененные состояния",                 "pt": "Atualizar estados inalterados",                   "nl": "Ongewijzigde status bijwerken",                   "fr": "Mettre à jour les états inchangés",               "it": "Aggiorna stati invariati",                        "es": "Actualizar estados sin cambios",                  "pl": "Zaktualizuj niezmienione stany",                  "zh-cn": "更新未更改的状态"},
    "customPortSelect": {                            "en": "Custom port (see below)",                         "de": "Benutzerdefiniert (s. unten)",                    "ru": "Пользовательский порт (см. Ниже)",                "pt": "Porta personalizada (veja abaixo)",               "nl": "Aangepaste poort (zie hieronder)",                "fr": "Port personnalisé (voir ci-dessous)",             "it": "Porta personalizzata (vedi sotto)",               "es": "Puerto personalizado (ver más abajo)",            "pl": "Port niestandardowy (patrz poniżej)",             "zh-cn": "自定义端口（见下文）"},
    "serialBaudRate": {                              "en": "Serial baud rate",                                "de": "Serielle Baudrate",                               "ru": "Скорость передачи",                               "pt": "Taxa de transmissão em série",                    "nl": "Seriële baudrate",                                "fr": "Vitesse de transmission en série",                "it": "Baud rate seriale",                               "es": "Velocidad en baudios en serie",                   "pl": "Szeregowa prędkość transmisji",                   "zh-cn": "串口波特率"},
    "serialPort": {                                  "en": "Serial port",                                     "de": "Serielle Schnittstelle",                          "ru": "Серийный порт",                                   "pt": "Porta serial",                                    "nl": "Seriële poort",                                   "fr": "Port série",                                      "it": "Porta seriale",                                   "es": "Puerto serial",                                   "pl": "Port szeregowy",                                  "zh-cn": "串行端口"},
    "wMBus Mode": {                                  "en": "wMBus Mode",                                      "de": "wMBus Mode",                                      "ru": "Режим wMBus",                                     "pt": "Modo wMBus",                                      "nl": "wMBus-modus",                                     "fr": "Mode wMBus",                                      "it": "Modalità wMBus",                                  "es": "Modo wMBus",                                      "pl": "Tryb wMBus",                                      "zh-cn": "总线模式"},
    "wMBus Receiver": {                              "en": "wMBus Receiver",                                  "de": "wMBus Empfänger",                                 "ru": "Приемник wMBus",                                  "pt": "Receptor wMBus",                                  "nl": "wMBus-ontvanger",                                 "fr": "Récepteur wMBus",                                 "it": "Ricevitore wMBus",                                "es": "Receptor wMBus",                                  "pl": "Odbiornik wMBus",                                 "zh-cn": "wMBus 接收器"},
};